### ISSUE TITLE
Passar por parâmetro a coleção DECS que está definida manualmente dentro do fonte

### ISSUE THREAD

**Issue by Michael-Junior** [bireme/ZBMedPrePrints-processing#64]
A discutir.

![Image](https://github.com/bireme/ZBMedPrePrints-processing/assets/69993392/f5db6edc-9346-48fc-94ac-b9d31292576f)

**Comment by heitorbarbieri** [comment]
@Michael-Junior , coloquei dois parâmetros adicionais na chamada do programa:
-decsDatabase:<name>   - parâmetro opcional que indica o nome da base de dados DeCs. Se ausente, vai considerar o valor "DECS" que é o valor atualmente usado e definido dentro do código
-decsCollection:<name> - parâmetro opcional que indica o nome da coleção DeCS a ser utilizada no programa. Se ausente, o programa vai pegar a coleção cujo nome representa o maior valor de ano. Atualmente 2023, ano que vem se tiver a coleção '2024' na base de dados 'DECS'  ele passará a utilizar a coleção 2024.

Por favor fazer uma cópia do diretório atual no servidor (para garantir), fazer o git pull e testar.
Obrigado.

**Comment by Michael-Junior** [comment]
> @Michael-Junior, coloquei duas configurações adicionais na chamada do programa: -decsDatabase: - parâmetro opcional que indica o nome da base de dados DeCs. Se estiver ausente, será considerado o valor "DECS" que é o valor atualmente usado e definido dentro do código -decsCollection: - parâmetro opcional que indica o nome da coleção DeCS a ser utilizado no programa. Se estiver ausente, o programa vai pegar uma coleção cujo nome representa o maior valor de ano. Atualmente em 2023, ano que vem se tiver a coleção '2024' na base de dados 'DECS' ele passará a utilizar a coleção 2024.
> 
> Por favor, faça uma cópia do diretório atual no servidor (para garantir), faça o git pull e teste. Obrigado.

Testes realizados!

Testado sem os novos parametros, com os novo parametros, com um dos novos parametros definidos de cada vez e testado com uma coleção criada vazia com o nome 2024, todos os testes tiveram sucesso.
